CREATE TABLE connections (
                             id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                             from_node_id BIGINT NOT NULL,
                             to_node_id BIGINT NOT NULL,
                             duration DOUBLE PRECISION NOT NULL,


                             CONSTRAINT fk_connection_from_node FOREIGN KEY (from_node_id) REFERENCES nodes(id),
                             CONSTRAINT fk_connection_to_node FOREIGN KEY (to_node_id) REFERENCES nodes(id)
);


CREATE INDEX idx_connection_from_node_id ON connections(from_node_id);
CREATE INDEX idx_connection_to_node_id ON connections(to_node_id);